# Generated by Django 5.0.7 on 2024-07-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipesite", "0002_delete_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
